name: white_whistle
description: World building app for your stories and everything else

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  json_annotation: ^4.4.0
  logger: ^1.1.0
  oxidized: ^5.2.0
  path_provider: ^2.0.9
  string_validator: ^0.3.0
  uuid: ^3.0.6
  window_manager: ^0.2.1

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8
  flutter_flavorizr: ^2.1.3
  flutter_launcher_icons_maker: ^0.10.2
  flutter_native_splash: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  isar_generator: ^2.2.1
  json_serializable: ^6.1.5
  very_good_analysis: ^2.4.0

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios: null

  flavors:
    development:
      app:
        name: "White Whistle Dev"

      android:
        applicationId: "io.killy.white_whistle.dev"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.white_whistle.dev"
        generateDummyAssets: false

    production:
      app:
        name: "White Whistle"

      android:
        applicationId: "io.killy.white_whistle"
        generateDummyAssets: false

      ios:
        bundleId: "io.killy.white_whistle"
        generateDummyAssets: false

flutter:
  uses-material-design: true
