name: white_whistle
description: World building app for your stories

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^3.2.3+1
  bitsdojo_window: ^0.1.1+1
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  isar: ^2.2.0+1
  isar_flutter_libs: ^2.2.0+1
  logger: ^1.1.0
  oxidized: ^5.2.0
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  isar_generator: ^2.2.0+1
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
